# Generated by Django 5.2.6 on 2025-12-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('SETOR', 'Setor Tunai'), ('TARIK', 'Tarik Tunai'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('amount_enc_sender', models.TextField(help_text='Nominal encrypted with Nasabah PK')),
                ('amount_enc_receiver', models.TextField(blank=True, help_text='Nominal encrypted with Receiver PK', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nasabah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication.nasabah')),
                ('related_nasabah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='authentication.nasabah', verbose_name='Penerima / Pengirim Terkait')),
            ],
        ),
    ]
