# Generated by Django 5.2.6 on 2026-01-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
