# Generated by Django 5.2.6 on 2025-12-15 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('encrypted_saldo', models.TextField()),
                ('pub_key_n', models.TextField()),
                ('pub_key_g', models.TextField()),
                ('priv_pail_key', models.TextField()),
                ('pin_hash', models.CharField(max_length=128)),
                ('key_salt', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nasabah', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
