# Generated by Django 5.2.6 on 2026-01-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasabah',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
